import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./user_globals.css";
import "./user_header.css";
import "./user_footer.css";
import Link from "next/link";
import Image from "next/image";
import { FaFacebook, FaInstagram, FaTwitter, FaWhatsapp } from "react-icons/fa";
import { Roboto } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "User Layout",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // Puedes elegir los pesos que necesites
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="UserLayout">
          {/*Cabezera de la pagina, barra de navegacion */}
          <header>Header</header>
          {/*Cuerpo de la pagina */}
          {children}
          {/*Pie de pagina*/}

          <footer>
            <div className="pg_footer section-footer">
              <div className="pg_footer-information">
                <div className="pg_footer-information-div">
                  <div className="pg_footer-logotext">
                    <Image
                      src="/Logo_InnovaJC.png"
                      alt="Logo"
                      width={150}
                      height={100}
                    ></Image>
                    <h4>Soluciones Integrales InnovaJC</h4>
                  </div>
                  <p>
                    Software de Gestión Contable y Administrativa para
                    optimizacion de negocios con soluciones de contabilidad
                    electrónica, facturación y control de inventarios.
                    Automatiza tus procesos financieros con nuestro sistema
                    administrativo integral y escalable.
                  </p>
                </div>
                <div className="pg_footer-information-div">
                  <Link href="/about">
                    <p>Sobre Nosotros</p>
                  </Link>
                  <Link href="/customers">
                    <p>Clientes</p>
                  </Link>
                  <Link href="/downloads">
                    <p>Descargar</p>
                  </Link>
                  <Link href="/contact">
                    <p>Contactanos</p>
                  </Link>
                </div>
                <div className="pg_footer-information-div">
                  <div className="socialmedia flex gap-4 text-[#616161] text-4xl">
                    <a href="https://facebook.com">
                      <FaFacebook />
                    </a>
                    <a href="https://instagram.com">
                      <FaInstagram />
                    </a>
                    <a href="https://Twitter.com">
                      <FaTwitter />
                    </a>
                  </div>
                </div>
              </div>
              <hr></hr>
              <div className="pg_footer-terms">
                <div className="pg_footer-copyright">
                  <p>
                    Soluciones Integrales InnovaJC S.A Derechos Reservados
                    &copy;{new Date().getFullYear()}
                  </p>
                </div>
                <div className="pg_footer-termslink">
                  <p>Terminos</p>
                  <p>Condiciones</p>
                  <p>Politicas</p>
                  <p>Privacidad</p>
                </div>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
