import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./contact_globals.css";
import "./contact_header.css";
import "./contact_footer.css";
import Link from "next/link";
import Image from "next/image";
import { FaFacebook, FaInstagram, FaTwitter, FaWhatsapp } from "react-icons/fa";
import { Roboto } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Contact Layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <p>Contact NAVBAR</p>
        {children}
        <p>Footer</p>

        <a
          href="https://wa.me/50684753334"
          className="whatsapp-button text-3xl"
        >
          <FaWhatsapp />
        </a>
      </body>
    </html>
  );
}
